authserverUri: ${AUTHSERVER_URI:http://localhost:9000}

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${authserverUri}/auth/realms/sample
            authorization-uri: ${authserverUri}/auth/realms/sample/protocol/openid-connect/auth
            token-uri: ${authserverUri}/auth/realms/sample/protocol/openid-connect/token
            user-info-uri: ${authserverUri}/auth/realms/sample/protocol/openid-connect/userinfo
            jwk-set-uri: ${authserverUri}/auth/realms/sample/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: login-app
            client-secret: e712ef31-29c6-48f4-bc47-d98da0248b5e
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: api,profile
server:
  port: ${SERVER_PORT:8001}

logging:
  level:
    ROOT: info
    org.springframework.security: trace
    com.pksheldon4: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace