management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace

logging:
  level:
    org.springframework: info
#    org.springframework.web: debug
#    org.springframework.security: debug
    com.pksheldon4.demo: info
